serviceName: infrastructure-tg-notifier
app:
  telegramAPIKey:
  checkIntervalSSL: 24h
  checkIntervalSelectelBilling: 24h
  checkIntervalSiteDefault: 5m
services:
  - name: ProjectName
    telegramChatId:
    selectelAPIKey:
    envs:
      - name: prod
        links:
          - url: https://example.com
            checkIntervalSSL: 12h
            checkIntervalSite: 1m
          - url: https://api.example.com
            checkIntervalSSL: 12h
            checkIntervalSite: 1m
      - name: dev
        links:
          - url: https://dev.example.com
            checkIntervalSSL: 48h
            checkIntervalSite: 10m
          - url: https://api.dev.example.com
            checkIntervalSSL: 48h
            checkIntervalSite: 10m




