serviceName: infrastructure-tg-notifier
app:
  telegramAPIKey:
services:
  - name: ProjectName
    telegramChatId:
    selectelAPIKey:
      checkIntervalSSL: 1m
      checkIntervalSite: 10s
      checkIntervalSelectelBilling: 1m
      muteTimeAfterError: 5m
    envs:
      - name: prod
        links:
          - url: https://example.com
          - url: https://api.example.com
      - name: dev
        links:
          - url: https://dev.example.com
          - url: https://api.dev.example.com




